spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/add_dict_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:pswd}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  dictionary-validation-rule:
    name:
      length: 128
    description:
      length: 256

  translation-validation-rule:
    origin-text:
      length: 128
    translation-text:
      length: 128

  translation:
    translation-page-size: 20

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      connection_factory: jedis # `jedis` or `lettuce`

  feign-clients:
    auth:
      host: ${AUTH_CLIENT_HOST:localhost}
      port: ${AUTH_CLIENT_PORT:8081}
      url: http://${spring.feign-clients.auth.host}:${spring.feign-clients.auth.port}/api/v1/auth

server:
  port: 8080

logging:
  level:
    root: info

    org:
      springframework:
        security: debug
        web: debug
      hibernate:
        sql: debug
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: TRACE